
name: Updater

on:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm install
          npm start
        env:
          AUTH_TOKEN: ${{secrets.auth_token}}
